---
name: Qwiet Multi-Language Demo

on:
  push:

jobs:
  Qwiet-Static-Analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Deps
      run: |
        sudo apt-get install jq

    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ./sl && chmod a+rx ./sl 

    - name: Run sl analyze
      shell: bash
      run: |
        sudo chmod a+x ./detectLang.sh
        rm -rf .git
        sh detectLang.sh -a testmultilang -p ${GITHUB_WORKSPACE} -t ${SHIFTLEFT_ACCESS_TOKEN}
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
